title: Making a Crowd Display with micro:bits and MakeCode
hero_image: images/banner.png
description: Program a set of micro:bits so that they talk to each other via radio to create a synchonised light show
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "physical computing"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Design your image
  - title: Set up the radio
  - title: Triggering an avalanche of messages
